package com.jkoss.dao.oa;

import com.jkoss.pojo.oa.Empdetail;
import com.jkoss.pojo.oa.EmpdetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    int countByExample(EmpdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    int deleteByExample(EmpdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer empdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    int insert(Empdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    int insertSelective(Empdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    List<Empdetail> selectByExample(EmpdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    Empdetail selectByPrimaryKey(Integer empdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Empdetail record, @Param("example") EmpdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Empdetail record, @Param("example") EmpdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Empdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Empdetail record);
}