package com.jkoss.dao.oa;

import com.jkoss.pojo.oa.Reimsub;
import com.jkoss.pojo.oa.ReimsubExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReimsubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    int countByExample(ReimsubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    int deleteByExample(ReimsubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer reimsubid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    int insert(Reimsub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    int insertSelective(Reimsub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    List<Reimsub> selectByExample(ReimsubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    Reimsub selectByPrimaryKey(Integer reimsubid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Reimsub record, @Param("example") ReimsubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Reimsub record, @Param("example") ReimsubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Reimsub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Reimsub record);
}