package com.jkoss.dao.oa;

import com.jkoss.pojo.oa.Reims;
import com.jkoss.pojo.oa.ReimsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReimsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    int countByExample(ReimsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    int deleteByExample(ReimsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer riemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    int insert(Reims record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    int insertSelective(Reims record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    List<Reims> selectByExample(ReimsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    Reims selectByPrimaryKey(Integer riemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Reims record, @Param("example") ReimsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Reims record, @Param("example") ReimsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Reims record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reims
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Reims record);
}