package com.jkoss.dao.oa;

import com.jkoss.pojo.oa.Salary;
import com.jkoss.pojo.oa.SalaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    int countByExample(SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    int deleteByExample(SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer salid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    int insert(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    int insertSelective(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    List<Salary> selectByExample(SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    Salary selectByPrimaryKey(Integer salid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Salary record, @Param("example") SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Salary record, @Param("example") SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Salary record);
}