package com.jkoss.pojo.oa;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.depID
     *
     * @mbggenerated
     */
    private Integer depID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.depname
     *
     * @mbggenerated
     */
    private String depname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.dnote
     *
     * @mbggenerated
     */
    private String dnote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.depID
     *
     * @return the value of t_department.depID
     *
     * @mbggenerated
     */
    public Integer getDepID() {
        return depID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.depID
     *
     * @param depID the value for t_department.depID
     *
     * @mbggenerated
     */
    public void setDepID(Integer depID) {
        this.depID = depID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.depname
     *
     * @return the value of t_department.depname
     *
     * @mbggenerated
     */
    public String getDepname() {
        return depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.depname
     *
     * @param depname the value for t_department.depname
     *
     * @mbggenerated
     */
    public void setDepname(String depname) {
        this.depname = depname == null ? null : depname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.dnote
     *
     * @return the value of t_department.dnote
     *
     * @mbggenerated
     */
    public String getDnote() {
        return dnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.dnote
     *
     * @param dnote the value for t_department.dnote
     *
     * @mbggenerated
     */
    public void setDnote(String dnote) {
        this.dnote = dnote == null ? null : dnote.trim();
    }
}