package com.jkoss.pojo.oa;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EmpdetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public EmpdetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andEmpdidIsNull() {
            addCriterion("empdid is null");
            return (Criteria) this;
        }

        public Criteria andEmpdidIsNotNull() {
            addCriterion("empdid is not null");
            return (Criteria) this;
        }

        public Criteria andEmpdidEqualTo(Integer value) {
            addCriterion("empdid =", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidNotEqualTo(Integer value) {
            addCriterion("empdid <>", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidGreaterThan(Integer value) {
            addCriterion("empdid >", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidGreaterThanOrEqualTo(Integer value) {
            addCriterion("empdid >=", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidLessThan(Integer value) {
            addCriterion("empdid <", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidLessThanOrEqualTo(Integer value) {
            addCriterion("empdid <=", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidIn(List<Integer> values) {
            addCriterion("empdid in", values, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidNotIn(List<Integer> values) {
            addCriterion("empdid not in", values, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidBetween(Integer value1, Integer value2) {
            addCriterion("empdid between", value1, value2, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidNotBetween(Integer value1, Integer value2) {
            addCriterion("empdid not between", value1, value2, "empdid");
            return (Criteria) this;
        }

         

        public Criteria andEaddressIsNull() {
            addCriterion("eaddress is null");
            return (Criteria) this;
        }

        public Criteria andEaddressIsNotNull() {
            addCriterion("eaddress is not null");
            return (Criteria) this;
        }

        public Criteria andEaddressEqualTo(String value) {
            addCriterion("eaddress =", value, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressNotEqualTo(String value) {
            addCriterion("eaddress <>", value, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressGreaterThan(String value) {
            addCriterion("eaddress >", value, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressGreaterThanOrEqualTo(String value) {
            addCriterion("eaddress >=", value, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressLessThan(String value) {
            addCriterion("eaddress <", value, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressLessThanOrEqualTo(String value) {
            addCriterion("eaddress <=", value, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressLike(String value) {
            addCriterion("eaddress like", value, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressNotLike(String value) {
            addCriterion("eaddress not like", value, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressIn(List<String> values) {
            addCriterion("eaddress in", values, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressNotIn(List<String> values) {
            addCriterion("eaddress not in", values, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressBetween(String value1, String value2) {
            addCriterion("eaddress between", value1, value2, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEaddressNotBetween(String value1, String value2) {
            addCriterion("eaddress not between", value1, value2, "eaddress");
            return (Criteria) this;
        }

        public Criteria andEgradeIsNull() {
            addCriterion("egrade is null");
            return (Criteria) this;
        }

        public Criteria andEgradeIsNotNull() {
            addCriterion("egrade is not null");
            return (Criteria) this;
        }

        public Criteria andEgradeEqualTo(String value) {
            addCriterion("egrade =", value, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeNotEqualTo(String value) {
            addCriterion("egrade <>", value, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeGreaterThan(String value) {
            addCriterion("egrade >", value, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeGreaterThanOrEqualTo(String value) {
            addCriterion("egrade >=", value, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeLessThan(String value) {
            addCriterion("egrade <", value, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeLessThanOrEqualTo(String value) {
            addCriterion("egrade <=", value, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeLike(String value) {
            addCriterion("egrade like", value, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeNotLike(String value) {
            addCriterion("egrade not like", value, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeIn(List<String> values) {
            addCriterion("egrade in", values, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeNotIn(List<String> values) {
            addCriterion("egrade not in", values, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeBetween(String value1, String value2) {
            addCriterion("egrade between", value1, value2, "egrade");
            return (Criteria) this;
        }

        public Criteria andEgradeNotBetween(String value1, String value2) {
            addCriterion("egrade not between", value1, value2, "egrade");
            return (Criteria) this;
        }

        public Criteria andUpdschoolIsNull() {
            addCriterion("updschool is null");
            return (Criteria) this;
        }

        public Criteria andUpdschoolIsNotNull() {
            addCriterion("updschool is not null");
            return (Criteria) this;
        }

        public Criteria andUpdschoolEqualTo(String value) {
            addCriterion("updschool =", value, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolNotEqualTo(String value) {
            addCriterion("updschool <>", value, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolGreaterThan(String value) {
            addCriterion("updschool >", value, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolGreaterThanOrEqualTo(String value) {
            addCriterion("updschool >=", value, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolLessThan(String value) {
            addCriterion("updschool <", value, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolLessThanOrEqualTo(String value) {
            addCriterion("updschool <=", value, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolLike(String value) {
            addCriterion("updschool like", value, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolNotLike(String value) {
            addCriterion("updschool not like", value, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolIn(List<String> values) {
            addCriterion("updschool in", values, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolNotIn(List<String> values) {
            addCriterion("updschool not in", values, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolBetween(String value1, String value2) {
            addCriterion("updschool between", value1, value2, "updschool");
            return (Criteria) this;
        }

        public Criteria andUpdschoolNotBetween(String value1, String value2) {
            addCriterion("updschool not between", value1, value2, "updschool");
            return (Criteria) this;
        }

        public Criteria andXwgradeIsNull() {
            addCriterion("xwgrade is null");
            return (Criteria) this;
        }

        public Criteria andXwgradeIsNotNull() {
            addCriterion("xwgrade is not null");
            return (Criteria) this;
        }

        public Criteria andXwgradeEqualTo(String value) {
            addCriterion("xwgrade =", value, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeNotEqualTo(String value) {
            addCriterion("xwgrade <>", value, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeGreaterThan(String value) {
            addCriterion("xwgrade >", value, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeGreaterThanOrEqualTo(String value) {
            addCriterion("xwgrade >=", value, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeLessThan(String value) {
            addCriterion("xwgrade <", value, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeLessThanOrEqualTo(String value) {
            addCriterion("xwgrade <=", value, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeLike(String value) {
            addCriterion("xwgrade like", value, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeNotLike(String value) {
            addCriterion("xwgrade not like", value, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeIn(List<String> values) {
            addCriterion("xwgrade in", values, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeNotIn(List<String> values) {
            addCriterion("xwgrade not in", values, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeBetween(String value1, String value2) {
            addCriterion("xwgrade between", value1, value2, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andXwgradeNotBetween(String value1, String value2) {
            addCriterion("xwgrade not between", value1, value2, "xwgrade");
            return (Criteria) this;
        }

        public Criteria andEmayorIsNull() {
            addCriterion("emayor is null");
            return (Criteria) this;
        }

        public Criteria andEmayorIsNotNull() {
            addCriterion("emayor is not null");
            return (Criteria) this;
        }

        public Criteria andEmayorEqualTo(String value) {
            addCriterion("emayor =", value, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorNotEqualTo(String value) {
            addCriterion("emayor <>", value, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorGreaterThan(String value) {
            addCriterion("emayor >", value, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorGreaterThanOrEqualTo(String value) {
            addCriterion("emayor >=", value, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorLessThan(String value) {
            addCriterion("emayor <", value, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorLessThanOrEqualTo(String value) {
            addCriterion("emayor <=", value, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorLike(String value) {
            addCriterion("emayor like", value, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorNotLike(String value) {
            addCriterion("emayor not like", value, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorIn(List<String> values) {
            addCriterion("emayor in", values, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorNotIn(List<String> values) {
            addCriterion("emayor not in", values, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorBetween(String value1, String value2) {
            addCriterion("emayor between", value1, value2, "emayor");
            return (Criteria) this;
        }

        public Criteria andEmayorNotBetween(String value1, String value2) {
            addCriterion("emayor not between", value1, value2, "emayor");
            return (Criteria) this;
        }

        public Criteria andEworker1IsNull() {
            addCriterion("eworker1 is null");
            return (Criteria) this;
        }

        public Criteria andEworker1IsNotNull() {
            addCriterion("eworker1 is not null");
            return (Criteria) this;
        }

        public Criteria andEworker1EqualTo(String value) {
            addCriterion("eworker1 =", value, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1NotEqualTo(String value) {
            addCriterion("eworker1 <>", value, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1GreaterThan(String value) {
            addCriterion("eworker1 >", value, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1GreaterThanOrEqualTo(String value) {
            addCriterion("eworker1 >=", value, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1LessThan(String value) {
            addCriterion("eworker1 <", value, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1LessThanOrEqualTo(String value) {
            addCriterion("eworker1 <=", value, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1Like(String value) {
            addCriterion("eworker1 like", value, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1NotLike(String value) {
            addCriterion("eworker1 not like", value, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1In(List<String> values) {
            addCriterion("eworker1 in", values, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1NotIn(List<String> values) {
            addCriterion("eworker1 not in", values, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1Between(String value1, String value2) {
            addCriterion("eworker1 between", value1, value2, "eworker1");
            return (Criteria) this;
        }

        public Criteria andEworker1NotBetween(String value1, String value2) {
            addCriterion("eworker1 not between", value1, value2, "eworker1");
            return (Criteria) this;
        }

        public Criteria andSkillsIsNull() {
            addCriterion("skills is null");
            return (Criteria) this;
        }

        public Criteria andSkillsIsNotNull() {
            addCriterion("skills is not null");
            return (Criteria) this;
        }

        public Criteria andSkillsEqualTo(String value) {
            addCriterion("skills =", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotEqualTo(String value) {
            addCriterion("skills <>", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsGreaterThan(String value) {
            addCriterion("skills >", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsGreaterThanOrEqualTo(String value) {
            addCriterion("skills >=", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsLessThan(String value) {
            addCriterion("skills <", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsLessThanOrEqualTo(String value) {
            addCriterion("skills <=", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsLike(String value) {
            addCriterion("skills like", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotLike(String value) {
            addCriterion("skills not like", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsIn(List<String> values) {
            addCriterion("skills in", values, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotIn(List<String> values) {
            addCriterion("skills not in", values, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsBetween(String value1, String value2) {
            addCriterion("skills between", value1, value2, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotBetween(String value1, String value2) {
            addCriterion("skills not between", value1, value2, "skills");
            return (Criteria) this;
        }

        public Criteria andEuntildateIsNull() {
            addCriterion("euntildate is null");
            return (Criteria) this;
        }

        public Criteria andEuntildateIsNotNull() {
            addCriterion("euntildate is not null");
            return (Criteria) this;
        }

        public Criteria andEuntildateEqualTo(Date value) {
            addCriterionForJDBCDate("euntildate =", value, "euntildate");
            return (Criteria) this;
        }

        public Criteria andEuntildateNotEqualTo(Date value) {
            addCriterionForJDBCDate("euntildate <>", value, "euntildate");
            return (Criteria) this;
        }

        public Criteria andEuntildateGreaterThan(Date value) {
            addCriterionForJDBCDate("euntildate >", value, "euntildate");
            return (Criteria) this;
        }

        public Criteria andEuntildateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("euntildate >=", value, "euntildate");
            return (Criteria) this;
        }

        public Criteria andEuntildateLessThan(Date value) {
            addCriterionForJDBCDate("euntildate <", value, "euntildate");
            return (Criteria) this;
        }

        public Criteria andEuntildateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("euntildate <=", value, "euntildate");
            return (Criteria) this;
        }

        public Criteria andEuntildateIn(List<Date> values) {
            addCriterionForJDBCDate("euntildate in", values, "euntildate");
            return (Criteria) this;
        }

        public Criteria andEuntildateNotIn(List<Date> values) {
            addCriterionForJDBCDate("euntildate not in", values, "euntildate");
            return (Criteria) this;
        }

        public Criteria andEuntildateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("euntildate between", value1, value2, "euntildate");
            return (Criteria) this;
        }

        public Criteria andEuntildateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("euntildate not between", value1, value2, "euntildate");
            return (Criteria) this;
        }

        public Criteria andJjconnect1IsNull() {
            addCriterion("jjconnect1 is null");
            return (Criteria) this;
        }

        public Criteria andJjconnect1IsNotNull() {
            addCriterion("jjconnect1 is not null");
            return (Criteria) this;
        }

        public Criteria andJjconnect1EqualTo(String value) {
            addCriterion("jjconnect1 =", value, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1NotEqualTo(String value) {
            addCriterion("jjconnect1 <>", value, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1GreaterThan(String value) {
            addCriterion("jjconnect1 >", value, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1GreaterThanOrEqualTo(String value) {
            addCriterion("jjconnect1 >=", value, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1LessThan(String value) {
            addCriterion("jjconnect1 <", value, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1LessThanOrEqualTo(String value) {
            addCriterion("jjconnect1 <=", value, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1Like(String value) {
            addCriterion("jjconnect1 like", value, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1NotLike(String value) {
            addCriterion("jjconnect1 not like", value, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1In(List<String> values) {
            addCriterion("jjconnect1 in", values, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1NotIn(List<String> values) {
            addCriterion("jjconnect1 not in", values, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1Between(String value1, String value2) {
            addCriterion("jjconnect1 between", value1, value2, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect1NotBetween(String value1, String value2) {
            addCriterion("jjconnect1 not between", value1, value2, "jjconnect1");
            return (Criteria) this;
        }

        public Criteria andJjconnect2IsNull() {
            addCriterion("jjconnect2 is null");
            return (Criteria) this;
        }

        public Criteria andJjconnect2IsNotNull() {
            addCriterion("jjconnect2 is not null");
            return (Criteria) this;
        }

        public Criteria andJjconnect2EqualTo(String value) {
            addCriterion("jjconnect2 =", value, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2NotEqualTo(String value) {
            addCriterion("jjconnect2 <>", value, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2GreaterThan(String value) {
            addCriterion("jjconnect2 >", value, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2GreaterThanOrEqualTo(String value) {
            addCriterion("jjconnect2 >=", value, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2LessThan(String value) {
            addCriterion("jjconnect2 <", value, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2LessThanOrEqualTo(String value) {
            addCriterion("jjconnect2 <=", value, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2Like(String value) {
            addCriterion("jjconnect2 like", value, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2NotLike(String value) {
            addCriterion("jjconnect2 not like", value, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2In(List<String> values) {
            addCriterion("jjconnect2 in", values, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2NotIn(List<String> values) {
            addCriterion("jjconnect2 not in", values, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2Between(String value1, String value2) {
            addCriterion("jjconnect2 between", value1, value2, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andJjconnect2NotBetween(String value1, String value2) {
            addCriterion("jjconnect2 not between", value1, value2, "jjconnect2");
            return (Criteria) this;
        }

        public Criteria andEpayIsNull() {
            addCriterion("epay is null");
            return (Criteria) this;
        }

        public Criteria andEpayIsNotNull() {
            addCriterion("epay is not null");
            return (Criteria) this;
        }

        public Criteria andEpayEqualTo(String value) {
            addCriterion("epay =", value, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayNotEqualTo(String value) {
            addCriterion("epay <>", value, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayGreaterThan(String value) {
            addCriterion("epay >", value, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayGreaterThanOrEqualTo(String value) {
            addCriterion("epay >=", value, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayLessThan(String value) {
            addCriterion("epay <", value, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayLessThanOrEqualTo(String value) {
            addCriterion("epay <=", value, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayLike(String value) {
            addCriterion("epay like", value, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayNotLike(String value) {
            addCriterion("epay not like", value, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayIn(List<String> values) {
            addCriterion("epay in", values, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayNotIn(List<String> values) {
            addCriterion("epay not in", values, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayBetween(String value1, String value2) {
            addCriterion("epay between", value1, value2, "epay");
            return (Criteria) this;
        }

        public Criteria andEpayNotBetween(String value1, String value2) {
            addCriterion("epay not between", value1, value2, "epay");
            return (Criteria) this;
        }

        public Criteria andBankcardIsNull() {
            addCriterion("bankcard is null");
            return (Criteria) this;
        }

        public Criteria andBankcardIsNotNull() {
            addCriterion("bankcard is not null");
            return (Criteria) this;
        }

        public Criteria andBankcardEqualTo(String value) {
            addCriterion("bankcard =", value, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardNotEqualTo(String value) {
            addCriterion("bankcard <>", value, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardGreaterThan(String value) {
            addCriterion("bankcard >", value, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardGreaterThanOrEqualTo(String value) {
            addCriterion("bankcard >=", value, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardLessThan(String value) {
            addCriterion("bankcard <", value, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardLessThanOrEqualTo(String value) {
            addCriterion("bankcard <=", value, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardLike(String value) {
            addCriterion("bankcard like", value, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardNotLike(String value) {
            addCriterion("bankcard not like", value, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardIn(List<String> values) {
            addCriterion("bankcard in", values, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardNotIn(List<String> values) {
            addCriterion("bankcard not in", values, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardBetween(String value1, String value2) {
            addCriterion("bankcard between", value1, value2, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBankcardNotBetween(String value1, String value2) {
            addCriterion("bankcard not between", value1, value2, "bankcard");
            return (Criteria) this;
        }

        public Criteria andBanknameIsNull() {
            addCriterion("bankname is null");
            return (Criteria) this;
        }

        public Criteria andBanknameIsNotNull() {
            addCriterion("bankname is not null");
            return (Criteria) this;
        }

        public Criteria andBanknameEqualTo(String value) {
            addCriterion("bankname =", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameNotEqualTo(String value) {
            addCriterion("bankname <>", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameGreaterThan(String value) {
            addCriterion("bankname >", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameGreaterThanOrEqualTo(String value) {
            addCriterion("bankname >=", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameLessThan(String value) {
            addCriterion("bankname <", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameLessThanOrEqualTo(String value) {
            addCriterion("bankname <=", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameLike(String value) {
            addCriterion("bankname like", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameNotLike(String value) {
            addCriterion("bankname not like", value, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameIn(List<String> values) {
            addCriterion("bankname in", values, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameNotIn(List<String> values) {
            addCriterion("bankname not in", values, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameBetween(String value1, String value2) {
            addCriterion("bankname between", value1, value2, "bankname");
            return (Criteria) this;
        }

        public Criteria andBanknameNotBetween(String value1, String value2) {
            addCriterion("bankname not between", value1, value2, "bankname");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telIsNull() {
            addCriterion("jjconnect1tel is null");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telIsNotNull() {
            addCriterion("jjconnect1tel is not null");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telEqualTo(String value) {
            addCriterion("jjconnect1tel =", value, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telNotEqualTo(String value) {
            addCriterion("jjconnect1tel <>", value, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telGreaterThan(String value) {
            addCriterion("jjconnect1tel >", value, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telGreaterThanOrEqualTo(String value) {
            addCriterion("jjconnect1tel >=", value, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telLessThan(String value) {
            addCriterion("jjconnect1tel <", value, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telLessThanOrEqualTo(String value) {
            addCriterion("jjconnect1tel <=", value, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telLike(String value) {
            addCriterion("jjconnect1tel like", value, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telNotLike(String value) {
            addCriterion("jjconnect1tel not like", value, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telIn(List<String> values) {
            addCriterion("jjconnect1tel in", values, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telNotIn(List<String> values) {
            addCriterion("jjconnect1tel not in", values, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telBetween(String value1, String value2) {
            addCriterion("jjconnect1tel between", value1, value2, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect1telNotBetween(String value1, String value2) {
            addCriterion("jjconnect1tel not between", value1, value2, "jjconnect1tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telIsNull() {
            addCriterion("jjconnect2tel is null");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telIsNotNull() {
            addCriterion("jjconnect2tel is not null");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telEqualTo(String value) {
            addCriterion("jjconnect2tel =", value, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telNotEqualTo(String value) {
            addCriterion("jjconnect2tel <>", value, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telGreaterThan(String value) {
            addCriterion("jjconnect2tel >", value, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telGreaterThanOrEqualTo(String value) {
            addCriterion("jjconnect2tel >=", value, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telLessThan(String value) {
            addCriterion("jjconnect2tel <", value, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telLessThanOrEqualTo(String value) {
            addCriterion("jjconnect2tel <=", value, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telLike(String value) {
            addCriterion("jjconnect2tel like", value, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telNotLike(String value) {
            addCriterion("jjconnect2tel not like", value, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telIn(List<String> values) {
            addCriterion("jjconnect2tel in", values, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telNotIn(List<String> values) {
            addCriterion("jjconnect2tel not in", values, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telBetween(String value1, String value2) {
            addCriterion("jjconnect2tel between", value1, value2, "jjconnect2tel");
            return (Criteria) this;
        }

        public Criteria andJjconnect2telNotBetween(String value1, String value2) {
            addCriterion("jjconnect2tel not between", value1, value2, "jjconnect2tel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_empdetail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_empdetail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}