package com.jkoss.pojo.oa;

import java.util.Date;

public class Empdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.empdid
     *
     * @mbggenerated
     */
    private Integer empdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.eid
     *
     * @mbggenerated
     */
 
    private String eaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.egrade
     *
     * @mbggenerated
     */
    private String egrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.updschool
     *
     * @mbggenerated
     */
    private String updschool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.xwgrade
     *
     * @mbggenerated
     */
    private String xwgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.emayor
     *
     * @mbggenerated
     */
    private String emayor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.eworker1
     *
     * @mbggenerated
     */
    private String eworker1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.skills
     *
     * @mbggenerated
     */
    private String skills;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.euntildate
     *
     * @mbggenerated
     */
    private Date euntildate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.jjconnect1
     *
     * @mbggenerated
     */
    private String jjconnect1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.jjconnect2
     *
     * @mbggenerated
     */
    private String jjconnect2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.epay
     *
     * @mbggenerated
     */
    private String epay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.bankcard
     *
     * @mbggenerated
     */
    private String bankcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.bankname
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.jjconnect1tel
     *
     * @mbggenerated
     */
    private String jjconnect1tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empdetail.jjconnect2tel
     *
     * @mbggenerated
     */
    private String jjconnect2tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.empdid
     *
     * @return the value of t_empdetail.empdid
     *
     * @mbggenerated
     */
    public Integer getEmpdid() {
        return empdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.empdid
     *
     * @param empdid the value for t_empdetail.empdid
     *
     * @mbggenerated
     */
    public void setEmpdid(Integer empdid) {
        this.empdid = empdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.eid
     *
     * @return the value of t_empdetail.eid
     *
     * @mbggenerated
     */
 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.eaddress
     *
     * @return the value of t_empdetail.eaddress
     *
     * @mbggenerated
     */
    public String getEaddress() {
        return eaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.eaddress
     *
     * @param eaddress the value for t_empdetail.eaddress
     *
     * @mbggenerated
     */
    public void setEaddress(String eaddress) {
        this.eaddress = eaddress == null ? null : eaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.egrade
     *
     * @return the value of t_empdetail.egrade
     *
     * @mbggenerated
     */
    public String getEgrade() {
        return egrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.egrade
     *
     * @param egrade the value for t_empdetail.egrade
     *
     * @mbggenerated
     */
    public void setEgrade(String egrade) {
        this.egrade = egrade == null ? null : egrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.updschool
     *
     * @return the value of t_empdetail.updschool
     *
     * @mbggenerated
     */
    public String getUpdschool() {
        return updschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.updschool
     *
     * @param updschool the value for t_empdetail.updschool
     *
     * @mbggenerated
     */
    public void setUpdschool(String updschool) {
        this.updschool = updschool == null ? null : updschool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.xwgrade
     *
     * @return the value of t_empdetail.xwgrade
     *
     * @mbggenerated
     */
    public String getXwgrade() {
        return xwgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.xwgrade
     *
     * @param xwgrade the value for t_empdetail.xwgrade
     *
     * @mbggenerated
     */
    public void setXwgrade(String xwgrade) {
        this.xwgrade = xwgrade == null ? null : xwgrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.emayor
     *
     * @return the value of t_empdetail.emayor
     *
     * @mbggenerated
     */
    public String getEmayor() {
        return emayor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.emayor
     *
     * @param emayor the value for t_empdetail.emayor
     *
     * @mbggenerated
     */
    public void setEmayor(String emayor) {
        this.emayor = emayor == null ? null : emayor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.eworker1
     *
     * @return the value of t_empdetail.eworker1
     *
     * @mbggenerated
     */
    public String getEworker1() {
        return eworker1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.eworker1
     *
     * @param eworker1 the value for t_empdetail.eworker1
     *
     * @mbggenerated
     */
    public void setEworker1(String eworker1) {
        this.eworker1 = eworker1 == null ? null : eworker1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.skills
     *
     * @return the value of t_empdetail.skills
     *
     * @mbggenerated
     */
    public String getSkills() {
        return skills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.skills
     *
     * @param skills the value for t_empdetail.skills
     *
     * @mbggenerated
     */
    public void setSkills(String skills) {
        this.skills = skills == null ? null : skills.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.euntildate
     *
     * @return the value of t_empdetail.euntildate
     *
     * @mbggenerated
     */
    public Date getEuntildate() {
        return euntildate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.euntildate
     *
     * @param euntildate the value for t_empdetail.euntildate
     *
     * @mbggenerated
     */
    public void setEuntildate(Date euntildate) {
        this.euntildate = euntildate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.jjconnect1
     *
     * @return the value of t_empdetail.jjconnect1
     *
     * @mbggenerated
     */
    public String getJjconnect1() {
        return jjconnect1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.jjconnect1
     *
     * @param jjconnect1 the value for t_empdetail.jjconnect1
     *
     * @mbggenerated
     */
    public void setJjconnect1(String jjconnect1) {
        this.jjconnect1 = jjconnect1 == null ? null : jjconnect1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.jjconnect2
     *
     * @return the value of t_empdetail.jjconnect2
     *
     * @mbggenerated
     */
    public String getJjconnect2() {
        return jjconnect2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.jjconnect2
     *
     * @param jjconnect2 the value for t_empdetail.jjconnect2
     *
     * @mbggenerated
     */
    public void setJjconnect2(String jjconnect2) {
        this.jjconnect2 = jjconnect2 == null ? null : jjconnect2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.epay
     *
     * @return the value of t_empdetail.epay
     *
     * @mbggenerated
     */
    public String getEpay() {
        return epay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.epay
     *
     * @param epay the value for t_empdetail.epay
     *
     * @mbggenerated
     */
    public void setEpay(String epay) {
        this.epay = epay == null ? null : epay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.bankcard
     *
     * @return the value of t_empdetail.bankcard
     *
     * @mbggenerated
     */
    public String getBankcard() {
        return bankcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.bankcard
     *
     * @param bankcard the value for t_empdetail.bankcard
     *
     * @mbggenerated
     */
    public void setBankcard(String bankcard) {
        this.bankcard = bankcard == null ? null : bankcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.bankname
     *
     * @return the value of t_empdetail.bankname
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.bankname
     *
     * @param bankname the value for t_empdetail.bankname
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.jjconnect1tel
     *
     * @return the value of t_empdetail.jjconnect1tel
     *
     * @mbggenerated
     */
    public String getJjconnect1tel() {
        return jjconnect1tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.jjconnect1tel
     *
     * @param jjconnect1tel the value for t_empdetail.jjconnect1tel
     *
     * @mbggenerated
     */
    public void setJjconnect1tel(String jjconnect1tel) {
        this.jjconnect1tel = jjconnect1tel == null ? null : jjconnect1tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empdetail.jjconnect2tel
     *
     * @return the value of t_empdetail.jjconnect2tel
     *
     * @mbggenerated
     */
    public String getJjconnect2tel() {
        return jjconnect2tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empdetail.jjconnect2tel
     *
     * @param jjconnect2tel the value for t_empdetail.jjconnect2tel
     *
     * @mbggenerated
     */
    public void setJjconnect2tel(String jjconnect2tel) {
        this.jjconnect2tel = jjconnect2tel == null ? null : jjconnect2tel.trim();
    }
}