package com.jkoss.pojo.oa;

import java.util.Date;

public class Empkaoqin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empkaoqin.ekqid
     *
     * @mbggenerated
     */
    private Integer ekqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empkaoqin.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empkaoqin.t_e_eid
     *
     * @mbggenerated
     */
    private Integer t_e_eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empkaoqin.ekqmth
     *
     * @mbggenerated
     */
    private Date ekqmth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empkaoqin.ekqneedcount
     *
     * @mbggenerated
     */
    private Integer ekqneedcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empkaoqin.ekqcount
     *
     * @mbggenerated
     */
    private Integer ekqcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empkaoqin.ekqjinjia
     *
     * @mbggenerated
     */
    private Integer ekqjinjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empkaoqin.ekqkilljinjia
     *
     * @mbggenerated
     */
    private Integer ekqkilljinjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empkaoqin.ekqdesc
     *
     * @mbggenerated
     */
    private String ekqdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empkaoqin.ekqid
     *
     * @return the value of t_empkaoqin.ekqid
     *
     * @mbggenerated
     */
    public Integer getEkqid() {
        return ekqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empkaoqin.ekqid
     *
     * @param ekqid the value for t_empkaoqin.ekqid
     *
     * @mbggenerated
     */
    public void setEkqid(Integer ekqid) {
        this.ekqid = ekqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empkaoqin.eid
     *
     * @return the value of t_empkaoqin.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empkaoqin.eid
     *
     * @param eid the value for t_empkaoqin.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empkaoqin.t_e_eid
     *
     * @return the value of t_empkaoqin.t_e_eid
     *
     * @mbggenerated
     */
    public Integer getT_e_eid() {
        return t_e_eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empkaoqin.t_e_eid
     *
     * @param t_e_eid the value for t_empkaoqin.t_e_eid
     *
     * @mbggenerated
     */
    public void setT_e_eid(Integer t_e_eid) {
        this.t_e_eid = t_e_eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empkaoqin.ekqmth
     *
     * @return the value of t_empkaoqin.ekqmth
     *
     * @mbggenerated
     */
    public Date getEkqmth() {
        return ekqmth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empkaoqin.ekqmth
     *
     * @param ekqmth the value for t_empkaoqin.ekqmth
     *
     * @mbggenerated
     */
    public void setEkqmth(Date ekqmth) {
        this.ekqmth = ekqmth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empkaoqin.ekqneedcount
     *
     * @return the value of t_empkaoqin.ekqneedcount
     *
     * @mbggenerated
     */
    public Integer getEkqneedcount() {
        return ekqneedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empkaoqin.ekqneedcount
     *
     * @param ekqneedcount the value for t_empkaoqin.ekqneedcount
     *
     * @mbggenerated
     */
    public void setEkqneedcount(Integer ekqneedcount) {
        this.ekqneedcount = ekqneedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empkaoqin.ekqcount
     *
     * @return the value of t_empkaoqin.ekqcount
     *
     * @mbggenerated
     */
    public Integer getEkqcount() {
        return ekqcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empkaoqin.ekqcount
     *
     * @param ekqcount the value for t_empkaoqin.ekqcount
     *
     * @mbggenerated
     */
    public void setEkqcount(Integer ekqcount) {
        this.ekqcount = ekqcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empkaoqin.ekqjinjia
     *
     * @return the value of t_empkaoqin.ekqjinjia
     *
     * @mbggenerated
     */
    public Integer getEkqjinjia() {
        return ekqjinjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empkaoqin.ekqjinjia
     *
     * @param ekqjinjia the value for t_empkaoqin.ekqjinjia
     *
     * @mbggenerated
     */
    public void setEkqjinjia(Integer ekqjinjia) {
        this.ekqjinjia = ekqjinjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empkaoqin.ekqkilljinjia
     *
     * @return the value of t_empkaoqin.ekqkilljinjia
     *
     * @mbggenerated
     */
    public Integer getEkqkilljinjia() {
        return ekqkilljinjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empkaoqin.ekqkilljinjia
     *
     * @param ekqkilljinjia the value for t_empkaoqin.ekqkilljinjia
     *
     * @mbggenerated
     */
    public void setEkqkilljinjia(Integer ekqkilljinjia) {
        this.ekqkilljinjia = ekqkilljinjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empkaoqin.ekqdesc
     *
     * @return the value of t_empkaoqin.ekqdesc
     *
     * @mbggenerated
     */
    public String getEkqdesc() {
        return ekqdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empkaoqin.ekqdesc
     *
     * @param ekqdesc the value for t_empkaoqin.ekqdesc
     *
     * @mbggenerated
     */
    public void setEkqdesc(String ekqdesc) {
        this.ekqdesc = ekqdesc == null ? null : ekqdesc.trim();
    }
}