package com.jkoss.pojo.oa;

import java.util.Date;

public class Empqinjia {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.sqjid
     *
     * @mbggenerated
     */
    private Integer sqjid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.t_e_eid
     *
     * @mbggenerated
     */
    private Integer t_e_eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.sqjdate
     *
     * @mbggenerated
     */
    private Date sqjdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.sqjreson
     *
     * @mbggenerated
     */
    private String sqjreson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.sqjqueren
     *
     * @mbggenerated
     */
    private String sqjqueren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.sqjstate
     *
     * @mbggenerated
     */
    private Integer sqjstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.sqjbegin
     *
     * @mbggenerated
     */
    private Date sqjbegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.sqjend
     *
     * @mbggenerated
     */
    private Date sqjend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.sqjcnfm
     *
     * @mbggenerated
     */
    private String sqjcnfm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_empqinjia.sqjdesc
     *
     * @mbggenerated
     */
    private String sqjdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.sqjid
     *
     * @return the value of t_empqinjia.sqjid
     *
     * @mbggenerated
     */
    public Integer getSqjid() {
        return sqjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.sqjid
     *
     * @param sqjid the value for t_empqinjia.sqjid
     *
     * @mbggenerated
     */
    public void setSqjid(Integer sqjid) {
        this.sqjid = sqjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.eid
     *
     * @return the value of t_empqinjia.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.eid
     *
     * @param eid the value for t_empqinjia.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.t_e_eid
     *
     * @return the value of t_empqinjia.t_e_eid
     *
     * @mbggenerated
     */
    public Integer getT_e_eid() {
        return t_e_eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.t_e_eid
     *
     * @param t_e_eid the value for t_empqinjia.t_e_eid
     *
     * @mbggenerated
     */
    public void setT_e_eid(Integer t_e_eid) {
        this.t_e_eid = t_e_eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.sqjdate
     *
     * @return the value of t_empqinjia.sqjdate
     *
     * @mbggenerated
     */
    public Date getSqjdate() {
        return sqjdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.sqjdate
     *
     * @param sqjdate the value for t_empqinjia.sqjdate
     *
     * @mbggenerated
     */
    public void setSqjdate(Date sqjdate) {
        this.sqjdate = sqjdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.sqjreson
     *
     * @return the value of t_empqinjia.sqjreson
     *
     * @mbggenerated
     */
    public String getSqjreson() {
        return sqjreson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.sqjreson
     *
     * @param sqjreson the value for t_empqinjia.sqjreson
     *
     * @mbggenerated
     */
    public void setSqjreson(String sqjreson) {
        this.sqjreson = sqjreson == null ? null : sqjreson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.sqjqueren
     *
     * @return the value of t_empqinjia.sqjqueren
     *
     * @mbggenerated
     */
    public String getSqjqueren() {
        return sqjqueren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.sqjqueren
     *
     * @param sqjqueren the value for t_empqinjia.sqjqueren
     *
     * @mbggenerated
     */
    public void setSqjqueren(String sqjqueren) {
        this.sqjqueren = sqjqueren == null ? null : sqjqueren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.sqjstate
     *
     * @return the value of t_empqinjia.sqjstate
     *
     * @mbggenerated
     */
    public Integer getSqjstate() {
        return sqjstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.sqjstate
     *
     * @param sqjstate the value for t_empqinjia.sqjstate
     *
     * @mbggenerated
     */
    public void setSqjstate(Integer sqjstate) {
        this.sqjstate = sqjstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.sqjbegin
     *
     * @return the value of t_empqinjia.sqjbegin
     *
     * @mbggenerated
     */
    public Date getSqjbegin() {
        return sqjbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.sqjbegin
     *
     * @param sqjbegin the value for t_empqinjia.sqjbegin
     *
     * @mbggenerated
     */
    public void setSqjbegin(Date sqjbegin) {
        this.sqjbegin = sqjbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.sqjend
     *
     * @return the value of t_empqinjia.sqjend
     *
     * @mbggenerated
     */
    public Date getSqjend() {
        return sqjend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.sqjend
     *
     * @param sqjend the value for t_empqinjia.sqjend
     *
     * @mbggenerated
     */
    public void setSqjend(Date sqjend) {
        this.sqjend = sqjend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.sqjcnfm
     *
     * @return the value of t_empqinjia.sqjcnfm
     *
     * @mbggenerated
     */
    public String getSqjcnfm() {
        return sqjcnfm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.sqjcnfm
     *
     * @param sqjcnfm the value for t_empqinjia.sqjcnfm
     *
     * @mbggenerated
     */
    public void setSqjcnfm(String sqjcnfm) {
        this.sqjcnfm = sqjcnfm == null ? null : sqjcnfm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_empqinjia.sqjdesc
     *
     * @return the value of t_empqinjia.sqjdesc
     *
     * @mbggenerated
     */
    public String getSqjdesc() {
        return sqjdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_empqinjia.sqjdesc
     *
     * @param sqjdesc the value for t_empqinjia.sqjdesc
     *
     * @mbggenerated
     */
    public void setSqjdesc(String sqjdesc) {
        this.sqjdesc = sqjdesc == null ? null : sqjdesc.trim();
    }
}