package com.jkoss.pojo.oa;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EmpsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public EmpsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andEidIsNull() {
            addCriterion("eid is null");
            return (Criteria) this;
        }

        public Criteria andEidIsNotNull() {
            addCriterion("eid is not null");
            return (Criteria) this;
        }

        public Criteria andEidEqualTo(Integer value) {
            addCriterion("eid =", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotEqualTo(Integer value) {
            addCriterion("eid <>", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThan(Integer value) {
            addCriterion("eid >", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThanOrEqualTo(Integer value) {
            addCriterion("eid >=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThan(Integer value) {
            addCriterion("eid <", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThanOrEqualTo(Integer value) {
            addCriterion("eid <=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidIn(List<Integer> values) {
            addCriterion("eid in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotIn(List<Integer> values) {
            addCriterion("eid not in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidBetween(Integer value1, Integer value2) {
            addCriterion("eid between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotBetween(Integer value1, Integer value2) {
            addCriterion("eid not between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andJobidIsNull() {
            addCriterion("jobid is null");
            return (Criteria) this;
        }

        public Criteria andJobidIsNotNull() {
            addCriterion("jobid is not null");
            return (Criteria) this;
        }

        public Criteria andJobidEqualTo(Integer value) {
            addCriterion("jobid =", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotEqualTo(Integer value) {
            addCriterion("jobid <>", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidGreaterThan(Integer value) {
            addCriterion("jobid >", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidGreaterThanOrEqualTo(Integer value) {
            addCriterion("jobid >=", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidLessThan(Integer value) {
            addCriterion("jobid <", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidLessThanOrEqualTo(Integer value) {
            addCriterion("jobid <=", value, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidIn(List<Integer> values) {
            addCriterion("jobid in", values, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotIn(List<Integer> values) {
            addCriterion("jobid not in", values, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidBetween(Integer value1, Integer value2) {
            addCriterion("jobid between", value1, value2, "jobid");
            return (Criteria) this;
        }

        public Criteria andJobidNotBetween(Integer value1, Integer value2) {
            addCriterion("jobid not between", value1, value2, "jobid");
            return (Criteria) this;
        }

        public Criteria andEmpdidIsNull() {
            addCriterion("empdid is null");
            return (Criteria) this;
        }

        public Criteria andEmpdidIsNotNull() {
            addCriterion("empdid is not null");
            return (Criteria) this;
        }

        public Criteria andEmpdidEqualTo(Integer value) {
            addCriterion("empdid =", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidNotEqualTo(Integer value) {
            addCriterion("empdid <>", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidGreaterThan(Integer value) {
            addCriterion("empdid >", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidGreaterThanOrEqualTo(Integer value) {
            addCriterion("empdid >=", value, "empdid");
            return (Criteria) this;
        }

        public Criteria Empdid(Integer value) {
            addCriterion("empdid <", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidLessThanOrEqualTo(Integer value) {
            addCriterion("empdid <=", value, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidIn(List<Integer> values) {
            addCriterion("empdid in", values, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidNotIn(List<Integer> values) {
            addCriterion("empdid not in", values, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidBetween(Integer value1, Integer value2) {
            addCriterion("empdid between", value1, value2, "empdid");
            return (Criteria) this;
        }

        public Criteria andEmpdidNotBetween(Integer value1, Integer value2) {
            addCriterion("empdid not between", value1, value2, "empdid");
            return (Criteria) this;
        }

        public Criteria andLgnNameIsNull() {
            addCriterion("lgnName is null");
            return (Criteria) this;
        }

        public Criteria andLgnNameIsNotNull() {
            addCriterion("lgnName is not null");
            return (Criteria) this;
        }

        public Criteria andLgnNameEqualTo(String value) {
            addCriterion("lgnName =", value, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameNotEqualTo(String value) {
            addCriterion("lgnName <>", value, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameGreaterThan(String value) {
            addCriterion("lgnName >", value, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameGreaterThanOrEqualTo(String value) {
            addCriterion("lgnName >=", value, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameLessThan(String value) {
            addCriterion("lgnName <", value, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameLessThanOrEqualTo(String value) {
            addCriterion("lgnName <=", value, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameLike(String value) {
            addCriterion("lgnName like", value, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameNotLike(String value) {
            addCriterion("lgnName not like", value, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameIn(List<String> values) {
            addCriterion("lgnName in", values, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameNotIn(List<String> values) {
            addCriterion("lgnName not in", values, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameBetween(String value1, String value2) {
            addCriterion("lgnName between", value1, value2, "lgnName");
            return (Criteria) this;
        }

        public Criteria andLgnNameNotBetween(String value1, String value2) {
            addCriterion("lgnName not between", value1, value2, "lgnName");
            return (Criteria) this;
        }

        public Criteria andEnameIsNull() {
            addCriterion("ename is null");
            return (Criteria) this;
        }

        public Criteria andEnameIsNotNull() {
            addCriterion("ename is not null");
            return (Criteria) this;
        }

        public Criteria andEnameEqualTo(String value) {
            addCriterion("ename =", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotEqualTo(String value) {
            addCriterion("ename <>", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThan(String value) {
            addCriterion("ename >", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThanOrEqualTo(String value) {
            addCriterion("ename >=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThan(String value) {
            addCriterion("ename <", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThanOrEqualTo(String value) {
            addCriterion("ename <=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLike(String value) {
            addCriterion("ename like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotLike(String value) {
            addCriterion("ename not like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameIn(List<String> values) {
            addCriterion("ename in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotIn(List<String> values) {
            addCriterion("ename not in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameBetween(String value1, String value2) {
            addCriterion("ename between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotBetween(String value1, String value2) {
            addCriterion("ename not between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andPwdwordIsNull() {
            addCriterion("pwdword is null");
            return (Criteria) this;
        }

        public Criteria andPwdwordIsNotNull() {
            addCriterion("pwdword is not null");
            return (Criteria) this;
        }

        public Criteria andPwdwordEqualTo(String value) {
            addCriterion("pwdword =", value, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordNotEqualTo(String value) {
            addCriterion("pwdword <>", value, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordGreaterThan(String value) {
            addCriterion("pwdword >", value, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordGreaterThanOrEqualTo(String value) {
            addCriterion("pwdword >=", value, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordLessThan(String value) {
            addCriterion("pwdword <", value, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordLessThanOrEqualTo(String value) {
            addCriterion("pwdword <=", value, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordLike(String value) {
            addCriterion("pwdword like", value, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordNotLike(String value) {
            addCriterion("pwdword not like", value, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordIn(List<String> values) {
            addCriterion("pwdword in", values, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordNotIn(List<String> values) {
            addCriterion("pwdword not in", values, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordBetween(String value1, String value2) {
            addCriterion("pwdword between", value1, value2, "pwdword");
            return (Criteria) this;
        }

        public Criteria andPwdwordNotBetween(String value1, String value2) {
            addCriterion("pwdword not between", value1, value2, "pwdword");
            return (Criteria) this;
        }

        public Criteria andWeixinIsNull() {
            addCriterion("weixin is null");
            return (Criteria) this;
        }

        public Criteria andWeixinIsNotNull() {
            addCriterion("weixin is not null");
            return (Criteria) this;
        }

        public Criteria andWeixinEqualTo(String value) {
            addCriterion("weixin =", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinNotEqualTo(String value) {
            addCriterion("weixin <>", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinGreaterThan(String value) {
            addCriterion("weixin >", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinGreaterThanOrEqualTo(String value) {
            addCriterion("weixin >=", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinLessThan(String value) {
            addCriterion("weixin <", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinLessThanOrEqualTo(String value) {
            addCriterion("weixin <=", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinLike(String value) {
            addCriterion("weixin like", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinNotLike(String value) {
            addCriterion("weixin not like", value, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinIn(List<String> values) {
            addCriterion("weixin in", values, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinNotIn(List<String> values) {
            addCriterion("weixin not in", values, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinBetween(String value1, String value2) {
            addCriterion("weixin between", value1, value2, "weixin");
            return (Criteria) this;
        }

        public Criteria andWeixinNotBetween(String value1, String value2) {
            addCriterion("weixin not between", value1, value2, "weixin");
            return (Criteria) this;
        }

        public Criteria andHireDateIsNull() {
            addCriterion("hireDate is null");
            return (Criteria) this;
        }

        public Criteria andHireDateIsNotNull() {
            addCriterion("hireDate is not null");
            return (Criteria) this;
        }

        public Criteria andHireDateEqualTo(Date value) {
            addCriterion("hireDate =", value, "hireDate");
            return (Criteria) this;
        }

        public Criteria andHireDateNotEqualTo(Date value) {
            addCriterion("hireDate <>", value, "hireDate");
            return (Criteria) this;
        }

        public Criteria andHireDateGreaterThan(Date value) {
            addCriterion("hireDate >", value, "hireDate");
            return (Criteria) this;
        }

        public Criteria andHireDateGreaterThanOrEqualTo(Date value) {
            addCriterion("hireDate >=", value, "hireDate");
            return (Criteria) this;
        }

        public Criteria andHireDateLessThan(Date value) {
            addCriterion("hireDate <", value, "hireDate");
            return (Criteria) this;
        }

        public Criteria andHireDateLessThanOrEqualTo(Date value) {
            addCriterion("hireDate <=", value, "hireDate");
            return (Criteria) this;
        }

        public Criteria andHireDateIn(List<Date> values) {
            addCriterion("hireDate in", values, "hireDate");
            return (Criteria) this;
        }

        public Criteria andHireDateNotIn(List<Date> values) {
            addCriterion("hireDate not in", values, "hireDate");
            return (Criteria) this;
        }

        public Criteria andHireDateBetween(Date value1, Date value2) {
            addCriterion("hireDate between", value1, value2, "hireDate");
            return (Criteria) this;
        }

        public Criteria andHireDateNotBetween(Date value1, Date value2) {
            addCriterion("hireDate not between", value1, value2, "hireDate");
            return (Criteria) this;
        }

        public Criteria andOutDateIsNull() {
            addCriterion("outDate is null");
            return (Criteria) this;
        }

        public Criteria andOutDateIsNotNull() {
            addCriterion("outDate is not null");
            return (Criteria) this;
        }

        public Criteria andOutDateEqualTo(Date value) {
            addCriterion("outDate =", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateNotEqualTo(Date value) {
            addCriterion("outDate <>", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateGreaterThan(Date value) {
            addCriterion("outDate >", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateGreaterThanOrEqualTo(Date value) {
            addCriterion("outDate >=", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateLessThan(Date value) {
            addCriterion("outDate <", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateLessThanOrEqualTo(Date value) {
            addCriterion("outDate <=", value, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateIn(List<Date> values) {
            addCriterion("outDate in", values, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateNotIn(List<Date> values) {
            addCriterion("outDate not in", values, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateBetween(Date value1, Date value2) {
            addCriterion("outDate between", value1, value2, "outDate");
            return (Criteria) this;
        }

        public Criteria andOutDateNotBetween(Date value1, Date value2) {
            addCriterion("outDate not between", value1, value2, "outDate");
            return (Criteria) this;
        }

        public Criteria andEsexIsNull() {
            addCriterion("esex is null");
            return (Criteria) this;
        }

        public Criteria andEsexIsNotNull() {
            addCriterion("esex is not null");
            return (Criteria) this;
        }

        public Criteria andEsexEqualTo(Integer value) {
            addCriterion("esex =", value, "esex");
            return (Criteria) this;
        }

        public Criteria andEsexNotEqualTo(Integer value) {
            addCriterion("esex <>", value, "esex");
            return (Criteria) this;
        }

        public Criteria andEsexGreaterThan(Integer value) {
            addCriterion("esex >", value, "esex");
            return (Criteria) this;
        }

        public Criteria andEsexGreaterThanOrEqualTo(Integer value) {
            addCriterion("esex >=", value, "esex");
            return (Criteria) this;
        }

        public Criteria andEsexLessThan(Integer value) {
            addCriterion("esex <", value, "esex");
            return (Criteria) this;
        }

        public Criteria andEsexLessThanOrEqualTo(Integer value) {
            addCriterion("esex <=", value, "esex");
            return (Criteria) this;
        }

        public Criteria andEsexIn(List<Integer> values) {
            addCriterion("esex in", values, "esex");
            return (Criteria) this;
        }

        public Criteria andEsexNotIn(List<Integer> values) {
            addCriterion("esex not in", values, "esex");
            return (Criteria) this;
        }

        public Criteria andEsexBetween(Integer value1, Integer value2) {
            addCriterion("esex between", value1, value2, "esex");
            return (Criteria) this;
        }

        public Criteria andEsexNotBetween(Integer value1, Integer value2) {
            addCriterion("esex not between", value1, value2, "esex");
            return (Criteria) this;
        }

        public Criteria andEnotionIsNull() {
            addCriterion("enotion is null");
            return (Criteria) this;
        }

        public Criteria andEnotionIsNotNull() {
            addCriterion("enotion is not null");
            return (Criteria) this;
        }

        public Criteria andEnotionEqualTo(String value) {
            addCriterion("enotion =", value, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionNotEqualTo(String value) {
            addCriterion("enotion <>", value, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionGreaterThan(String value) {
            addCriterion("enotion >", value, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionGreaterThanOrEqualTo(String value) {
            addCriterion("enotion >=", value, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionLessThan(String value) {
            addCriterion("enotion <", value, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionLessThanOrEqualTo(String value) {
            addCriterion("enotion <=", value, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionLike(String value) {
            addCriterion("enotion like", value, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionNotLike(String value) {
            addCriterion("enotion not like", value, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionIn(List<String> values) {
            addCriterion("enotion in", values, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionNotIn(List<String> values) {
            addCriterion("enotion not in", values, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionBetween(String value1, String value2) {
            addCriterion("enotion between", value1, value2, "enotion");
            return (Criteria) this;
        }

        public Criteria andEnotionNotBetween(String value1, String value2) {
            addCriterion("enotion not between", value1, value2, "enotion");
            return (Criteria) this;
        }

        public Criteria andEageIsNull() {
            addCriterion("eage is null");
            return (Criteria) this;
        }

        public Criteria andEageIsNotNull() {
            addCriterion("eage is not null");
            return (Criteria) this;
        }

        public Criteria andEageEqualTo(Date value) {
            addCriterionForJDBCDate("eage =", value, "eage");
            return (Criteria) this;
        }

        public Criteria andEageNotEqualTo(Date value) {
            addCriterionForJDBCDate("eage <>", value, "eage");
            return (Criteria) this;
        }

        public Criteria andEageGreaterThan(Date value) {
            addCriterionForJDBCDate("eage >", value, "eage");
            return (Criteria) this;
        }

        public Criteria andEageGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("eage >=", value, "eage");
            return (Criteria) this;
        }

        public Criteria andEageLessThan(Date value) {
            addCriterionForJDBCDate("eage <", value, "eage");
            return (Criteria) this;
        }

        public Criteria andEageLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("eage <=", value, "eage");
            return (Criteria) this;
        }

        public Criteria andEageIn(List<Date> values) {
            addCriterionForJDBCDate("eage in", values, "eage");
            return (Criteria) this;
        }

        public Criteria andEageNotIn(List<Date> values) {
            addCriterionForJDBCDate("eage not in", values, "eage");
            return (Criteria) this;
        }

        public Criteria andEageBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("eage between", value1, value2, "eage");
            return (Criteria) this;
        }

        public Criteria andEageNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("eage not between", value1, value2, "eage");
            return (Criteria) this;
        }

        public Criteria andEphoneIsNull() {
            addCriterion("ephone is null");
            return (Criteria) this;
        }

        public Criteria andEphoneIsNotNull() {
            addCriterion("ephone is not null");
            return (Criteria) this;
        }

        public Criteria andEphoneEqualTo(String value) {
            addCriterion("ephone =", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneNotEqualTo(String value) {
            addCriterion("ephone <>", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneGreaterThan(String value) {
            addCriterion("ephone >", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneGreaterThanOrEqualTo(String value) {
            addCriterion("ephone >=", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneLessThan(String value) {
            addCriterion("ephone <", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneLessThanOrEqualTo(String value) {
            addCriterion("ephone <=", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneLike(String value) {
            addCriterion("ephone like", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneNotLike(String value) {
            addCriterion("ephone not like", value, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneIn(List<String> values) {
            addCriterion("ephone in", values, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneNotIn(List<String> values) {
            addCriterion("ephone not in", values, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneBetween(String value1, String value2) {
            addCriterion("ephone between", value1, value2, "ephone");
            return (Criteria) this;
        }

        public Criteria andEphoneNotBetween(String value1, String value2) {
            addCriterion("ephone not between", value1, value2, "ephone");
            return (Criteria) this;
        }

        public Criteria andQqpIsNull() {
            addCriterion("qqp is null");
            return (Criteria) this;
        }

        public Criteria andQqpIsNotNull() {
            addCriterion("qqp is not null");
            return (Criteria) this;
        }

        public Criteria andQqpEqualTo(String value) {
            addCriterion("qqp =", value, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpNotEqualTo(String value) {
            addCriterion("qqp <>", value, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpGreaterThan(String value) {
            addCriterion("qqp >", value, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpGreaterThanOrEqualTo(String value) {
            addCriterion("qqp >=", value, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpLessThan(String value) {
            addCriterion("qqp <", value, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpLessThanOrEqualTo(String value) {
            addCriterion("qqp <=", value, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpLike(String value) {
            addCriterion("qqp like", value, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpNotLike(String value) {
            addCriterion("qqp not like", value, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpIn(List<String> values) {
            addCriterion("qqp in", values, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpNotIn(List<String> values) {
            addCriterion("qqp not in", values, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpBetween(String value1, String value2) {
            addCriterion("qqp between", value1, value2, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqpNotBetween(String value1, String value2) {
            addCriterion("qqp not between", value1, value2, "qqp");
            return (Criteria) this;
        }

        public Criteria andQqeIsNull() {
            addCriterion("qqe is null");
            return (Criteria) this;
        }

        public Criteria andQqeIsNotNull() {
            addCriterion("qqe is not null");
            return (Criteria) this;
        }

        public Criteria andQqeEqualTo(String value) {
            addCriterion("qqe =", value, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeNotEqualTo(String value) {
            addCriterion("qqe <>", value, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeGreaterThan(String value) {
            addCriterion("qqe >", value, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeGreaterThanOrEqualTo(String value) {
            addCriterion("qqe >=", value, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeLessThan(String value) {
            addCriterion("qqe <", value, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeLessThanOrEqualTo(String value) {
            addCriterion("qqe <=", value, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeLike(String value) {
            addCriterion("qqe like", value, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeNotLike(String value) {
            addCriterion("qqe not like", value, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeIn(List<String> values) {
            addCriterion("qqe in", values, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeNotIn(List<String> values) {
            addCriterion("qqe not in", values, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeBetween(String value1, String value2) {
            addCriterion("qqe between", value1, value2, "qqe");
            return (Criteria) this;
        }

        public Criteria andQqeNotBetween(String value1, String value2) {
            addCriterion("qqe not between", value1, value2, "qqe");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_emps
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_emps
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}