package com.jkoss.pojo.oa;

public class Reimsub {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimsub.reimsubid
     *
     * @mbggenerated
     */
    private Integer reimsubid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimsub.riemid
     *
     * @mbggenerated
     */
    private Integer riemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimsub.reimname
     *
     * @mbggenerated
     */
    private String reimname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimsub.reimcost
     *
     * @mbggenerated
     */
    private Float reimcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimsub.isfp
     *
     * @mbggenerated
     */
    private String isfp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reimsub.reimdesc
     *
     * @mbggenerated
     */
    private String reimdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimsub.reimsubid
     *
     * @return the value of t_reimsub.reimsubid
     *
     * @mbggenerated
     */
    public Integer getReimsubid() {
        return reimsubid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimsub.reimsubid
     *
     * @param reimsubid the value for t_reimsub.reimsubid
     *
     * @mbggenerated
     */
    public void setReimsubid(Integer reimsubid) {
        this.reimsubid = reimsubid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimsub.riemid
     *
     * @return the value of t_reimsub.riemid
     *
     * @mbggenerated
     */
    public Integer getRiemid() {
        return riemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimsub.riemid
     *
     * @param riemid the value for t_reimsub.riemid
     *
     * @mbggenerated
     */
    public void setRiemid(Integer riemid) {
        this.riemid = riemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimsub.reimname
     *
     * @return the value of t_reimsub.reimname
     *
     * @mbggenerated
     */
    public String getReimname() {
        return reimname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimsub.reimname
     *
     * @param reimname the value for t_reimsub.reimname
     *
     * @mbggenerated
     */
    public void setReimname(String reimname) {
        this.reimname = reimname == null ? null : reimname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimsub.reimcost
     *
     * @return the value of t_reimsub.reimcost
     *
     * @mbggenerated
     */
    public Float getReimcost() {
        return reimcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimsub.reimcost
     *
     * @param reimcost the value for t_reimsub.reimcost
     *
     * @mbggenerated
     */
    public void setReimcost(Float reimcost) {
        this.reimcost = reimcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimsub.isfp
     *
     * @return the value of t_reimsub.isfp
     *
     * @mbggenerated
     */
    public String getIsfp() {
        return isfp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimsub.isfp
     *
     * @param isfp the value for t_reimsub.isfp
     *
     * @mbggenerated
     */
    public void setIsfp(String isfp) {
        this.isfp = isfp == null ? null : isfp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reimsub.reimdesc
     *
     * @return the value of t_reimsub.reimdesc
     *
     * @mbggenerated
     */
    public String getReimdesc() {
        return reimdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reimsub.reimdesc
     *
     * @param reimdesc the value for t_reimsub.reimdesc
     *
     * @mbggenerated
     */
    public void setReimdesc(String reimdesc) {
        this.reimdesc = reimdesc == null ? null : reimdesc.trim();
    }
}