package com.jkoss.pojo.oa;

import java.util.ArrayList;
import java.util.List;

public class ReimsubExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public ReimsubExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReimsubidIsNull() {
            addCriterion("reimsubid is null");
            return (Criteria) this;
        }

        public Criteria andReimsubidIsNotNull() {
            addCriterion("reimsubid is not null");
            return (Criteria) this;
        }

        public Criteria andReimsubidEqualTo(Integer value) {
            addCriterion("reimsubid =", value, "reimsubid");
            return (Criteria) this;
        }

        public Criteria andReimsubidNotEqualTo(Integer value) {
            addCriterion("reimsubid <>", value, "reimsubid");
            return (Criteria) this;
        }

        public Criteria andReimsubidGreaterThan(Integer value) {
            addCriterion("reimsubid >", value, "reimsubid");
            return (Criteria) this;
        }

        public Criteria andReimsubidGreaterThanOrEqualTo(Integer value) {
            addCriterion("reimsubid >=", value, "reimsubid");
            return (Criteria) this;
        }

        public Criteria andReimsubidLessThan(Integer value) {
            addCriterion("reimsubid <", value, "reimsubid");
            return (Criteria) this;
        }

        public Criteria andReimsubidLessThanOrEqualTo(Integer value) {
            addCriterion("reimsubid <=", value, "reimsubid");
            return (Criteria) this;
        }

        public Criteria andReimsubidIn(List<Integer> values) {
            addCriterion("reimsubid in", values, "reimsubid");
            return (Criteria) this;
        }

        public Criteria andReimsubidNotIn(List<Integer> values) {
            addCriterion("reimsubid not in", values, "reimsubid");
            return (Criteria) this;
        }

        public Criteria andReimsubidBetween(Integer value1, Integer value2) {
            addCriterion("reimsubid between", value1, value2, "reimsubid");
            return (Criteria) this;
        }

        public Criteria andReimsubidNotBetween(Integer value1, Integer value2) {
            addCriterion("reimsubid not between", value1, value2, "reimsubid");
            return (Criteria) this;
        }

        public Criteria andRiemidIsNull() {
            addCriterion("riemid is null");
            return (Criteria) this;
        }

        public Criteria andRiemidIsNotNull() {
            addCriterion("riemid is not null");
            return (Criteria) this;
        }

        public Criteria andRiemidEqualTo(Integer value) {
            addCriterion("riemid =", value, "riemid");
            return (Criteria) this;
        }

        public Criteria andRiemidNotEqualTo(Integer value) {
            addCriterion("riemid <>", value, "riemid");
            return (Criteria) this;
        }

        public Criteria andRiemidGreaterThan(Integer value) {
            addCriterion("riemid >", value, "riemid");
            return (Criteria) this;
        }

        public Criteria andRiemidGreaterThanOrEqualTo(Integer value) {
            addCriterion("riemid >=", value, "riemid");
            return (Criteria) this;
        }

        public Criteria andRiemidLessThan(Integer value) {
            addCriterion("riemid <", value, "riemid");
            return (Criteria) this;
        }

        public Criteria andRiemidLessThanOrEqualTo(Integer value) {
            addCriterion("riemid <=", value, "riemid");
            return (Criteria) this;
        }

        public Criteria andRiemidIn(List<Integer> values) {
            addCriterion("riemid in", values, "riemid");
            return (Criteria) this;
        }

        public Criteria andRiemidNotIn(List<Integer> values) {
            addCriterion("riemid not in", values, "riemid");
            return (Criteria) this;
        }

        public Criteria andRiemidBetween(Integer value1, Integer value2) {
            addCriterion("riemid between", value1, value2, "riemid");
            return (Criteria) this;
        }

        public Criteria andRiemidNotBetween(Integer value1, Integer value2) {
            addCriterion("riemid not between", value1, value2, "riemid");
            return (Criteria) this;
        }

        public Criteria andReimnameIsNull() {
            addCriterion("reimname is null");
            return (Criteria) this;
        }

        public Criteria andReimnameIsNotNull() {
            addCriterion("reimname is not null");
            return (Criteria) this;
        }

        public Criteria andReimnameEqualTo(String value) {
            addCriterion("reimname =", value, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameNotEqualTo(String value) {
            addCriterion("reimname <>", value, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameGreaterThan(String value) {
            addCriterion("reimname >", value, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameGreaterThanOrEqualTo(String value) {
            addCriterion("reimname >=", value, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameLessThan(String value) {
            addCriterion("reimname <", value, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameLessThanOrEqualTo(String value) {
            addCriterion("reimname <=", value, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameLike(String value) {
            addCriterion("reimname like", value, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameNotLike(String value) {
            addCriterion("reimname not like", value, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameIn(List<String> values) {
            addCriterion("reimname in", values, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameNotIn(List<String> values) {
            addCriterion("reimname not in", values, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameBetween(String value1, String value2) {
            addCriterion("reimname between", value1, value2, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimnameNotBetween(String value1, String value2) {
            addCriterion("reimname not between", value1, value2, "reimname");
            return (Criteria) this;
        }

        public Criteria andReimcostIsNull() {
            addCriterion("reimcost is null");
            return (Criteria) this;
        }

        public Criteria andReimcostIsNotNull() {
            addCriterion("reimcost is not null");
            return (Criteria) this;
        }

        public Criteria andReimcostEqualTo(Float value) {
            addCriterion("reimcost =", value, "reimcost");
            return (Criteria) this;
        }

        public Criteria andReimcostNotEqualTo(Float value) {
            addCriterion("reimcost <>", value, "reimcost");
            return (Criteria) this;
        }

        public Criteria andReimcostGreaterThan(Float value) {
            addCriterion("reimcost >", value, "reimcost");
            return (Criteria) this;
        }

        public Criteria andReimcostGreaterThanOrEqualTo(Float value) {
            addCriterion("reimcost >=", value, "reimcost");
            return (Criteria) this;
        }

        public Criteria andReimcostLessThan(Float value) {
            addCriterion("reimcost <", value, "reimcost");
            return (Criteria) this;
        }

        public Criteria andReimcostLessThanOrEqualTo(Float value) {
            addCriterion("reimcost <=", value, "reimcost");
            return (Criteria) this;
        }

        public Criteria andReimcostIn(List<Float> values) {
            addCriterion("reimcost in", values, "reimcost");
            return (Criteria) this;
        }

        public Criteria andReimcostNotIn(List<Float> values) {
            addCriterion("reimcost not in", values, "reimcost");
            return (Criteria) this;
        }

        public Criteria andReimcostBetween(Float value1, Float value2) {
            addCriterion("reimcost between", value1, value2, "reimcost");
            return (Criteria) this;
        }

        public Criteria andReimcostNotBetween(Float value1, Float value2) {
            addCriterion("reimcost not between", value1, value2, "reimcost");
            return (Criteria) this;
        }

        public Criteria andIsfpIsNull() {
            addCriterion("isfp is null");
            return (Criteria) this;
        }

        public Criteria andIsfpIsNotNull() {
            addCriterion("isfp is not null");
            return (Criteria) this;
        }

        public Criteria andIsfpEqualTo(String value) {
            addCriterion("isfp =", value, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpNotEqualTo(String value) {
            addCriterion("isfp <>", value, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpGreaterThan(String value) {
            addCriterion("isfp >", value, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpGreaterThanOrEqualTo(String value) {
            addCriterion("isfp >=", value, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpLessThan(String value) {
            addCriterion("isfp <", value, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpLessThanOrEqualTo(String value) {
            addCriterion("isfp <=", value, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpLike(String value) {
            addCriterion("isfp like", value, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpNotLike(String value) {
            addCriterion("isfp not like", value, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpIn(List<String> values) {
            addCriterion("isfp in", values, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpNotIn(List<String> values) {
            addCriterion("isfp not in", values, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpBetween(String value1, String value2) {
            addCriterion("isfp between", value1, value2, "isfp");
            return (Criteria) this;
        }

        public Criteria andIsfpNotBetween(String value1, String value2) {
            addCriterion("isfp not between", value1, value2, "isfp");
            return (Criteria) this;
        }

        public Criteria andReimdescIsNull() {
            addCriterion("reimdesc is null");
            return (Criteria) this;
        }

        public Criteria andReimdescIsNotNull() {
            addCriterion("reimdesc is not null");
            return (Criteria) this;
        }

        public Criteria andReimdescEqualTo(String value) {
            addCriterion("reimdesc =", value, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescNotEqualTo(String value) {
            addCriterion("reimdesc <>", value, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescGreaterThan(String value) {
            addCriterion("reimdesc >", value, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescGreaterThanOrEqualTo(String value) {
            addCriterion("reimdesc >=", value, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescLessThan(String value) {
            addCriterion("reimdesc <", value, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescLessThanOrEqualTo(String value) {
            addCriterion("reimdesc <=", value, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescLike(String value) {
            addCriterion("reimdesc like", value, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescNotLike(String value) {
            addCriterion("reimdesc not like", value, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescIn(List<String> values) {
            addCriterion("reimdesc in", values, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescNotIn(List<String> values) {
            addCriterion("reimdesc not in", values, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescBetween(String value1, String value2) {
            addCriterion("reimdesc between", value1, value2, "reimdesc");
            return (Criteria) this;
        }

        public Criteria andReimdescNotBetween(String value1, String value2) {
            addCriterion("reimdesc not between", value1, value2, "reimdesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_reimsub
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_reimsub
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}