package com.jkoss.pojo.oa;

import java.util.Date;

public class Reims {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reims.riemid
     *
     * @mbggenerated
     */
    private Integer riemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reims.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reims.riemname
     *
     * @mbggenerated
     */
    private String riemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reims.riemreson
     *
     * @mbggenerated
     */
    private String riemreson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reims.riemdesc
     *
     * @mbggenerated
     */
    private String riemdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reims.riemsqdate
     *
     * @mbggenerated
     */
    private Date riemsqdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reims.riemdate
     *
     * @mbggenerated
     */
    private Date riemdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reims.riemstate
     *
     * @mbggenerated
     */
    private Integer riemstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reims.riemid
     *
     * @return the value of t_reims.riemid
     *
     * @mbggenerated
     */
    public Integer getRiemid() {
        return riemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reims.riemid
     *
     * @param riemid the value for t_reims.riemid
     *
     * @mbggenerated
     */
    public void setRiemid(Integer riemid) {
        this.riemid = riemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reims.eid
     *
     * @return the value of t_reims.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reims.eid
     *
     * @param eid the value for t_reims.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reims.riemname
     *
     * @return the value of t_reims.riemname
     *
     * @mbggenerated
     */
    public String getRiemname() {
        return riemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reims.riemname
     *
     * @param riemname the value for t_reims.riemname
     *
     * @mbggenerated
     */
    public void setRiemname(String riemname) {
        this.riemname = riemname == null ? null : riemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reims.riemreson
     *
     * @return the value of t_reims.riemreson
     *
     * @mbggenerated
     */
    public String getRiemreson() {
        return riemreson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reims.riemreson
     *
     * @param riemreson the value for t_reims.riemreson
     *
     * @mbggenerated
     */
    public void setRiemreson(String riemreson) {
        this.riemreson = riemreson == null ? null : riemreson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reims.riemdesc
     *
     * @return the value of t_reims.riemdesc
     *
     * @mbggenerated
     */
    public String getRiemdesc() {
        return riemdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reims.riemdesc
     *
     * @param riemdesc the value for t_reims.riemdesc
     *
     * @mbggenerated
     */
    public void setRiemdesc(String riemdesc) {
        this.riemdesc = riemdesc == null ? null : riemdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reims.riemsqdate
     *
     * @return the value of t_reims.riemsqdate
     *
     * @mbggenerated
     */
    public Date getRiemsqdate() {
        return riemsqdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reims.riemsqdate
     *
     * @param riemsqdate the value for t_reims.riemsqdate
     *
     * @mbggenerated
     */
    public void setRiemsqdate(Date riemsqdate) {
        this.riemsqdate = riemsqdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reims.riemdate
     *
     * @return the value of t_reims.riemdate
     *
     * @mbggenerated
     */
    public Date getRiemdate() {
        return riemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reims.riemdate
     *
     * @param riemdate the value for t_reims.riemdate
     *
     * @mbggenerated
     */
    public void setRiemdate(Date riemdate) {
        this.riemdate = riemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reims.riemstate
     *
     * @return the value of t_reims.riemstate
     *
     * @mbggenerated
     */
    public Integer getRiemstate() {
        return riemstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reims.riemstate
     *
     * @param riemstate the value for t_reims.riemstate
     *
     * @mbggenerated
     */
    public void setRiemstate(Integer riemstate) {
        this.riemstate = riemstate;
    }
}