package com.jkoss.pojo.oa;

import java.util.Date;

public class Salary {
	
	private String  ename;
	private Integer depID;
	 
    public String getEname() {
		return ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public Integer getDepID() {
		return depID;
	}

	public void setDepID(Integer depID) {
		this.depID = depID;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.salid
     *
     * @mbggenerated
     */
    private Integer salid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.t_e_eid
     *
     * @mbggenerated
     */
    private Integer t_e_eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.salmth
     *
     * @mbggenerated
     */
    private Date salmth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.basicsalary
     *
     * @mbggenerated
     */
    private Integer basicsalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.meritsal
     *
     * @mbggenerated
     */
    private Integer meritsal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.isbuysb
     *
     * @mbggenerated
     */
    private Integer isbuysb=0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.addsal
     *
     * @mbggenerated
     */
    private Integer addsal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.addmeritsal
     *
     * @mbggenerated
     */
    private Integer addmeritsal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.saldesc
     *
     * @mbggenerated
     */
    private String saldesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salary.salstate
     *
     * @mbggenerated
     */
    private Integer salstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.salid
     *
     * @return the value of t_salary.salid
     *
     * @mbggenerated
     */
    public Integer getSalid() {
        return salid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.salid
     *
     * @param salid the value for t_salary.salid
     *
     * @mbggenerated
     */
    public void setSalid(Integer salid) {
        this.salid = salid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.eid
     *
     * @return the value of t_salary.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.eid
     *
     * @param eid the value for t_salary.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.t_e_eid
     *
     * @return the value of t_salary.t_e_eid
     *
     * @mbggenerated
     */
    public Integer getT_e_eid() {
        return t_e_eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.t_e_eid
     *
     * @param t_e_eid the value for t_salary.t_e_eid
     *
     * @mbggenerated
     */
    public void setT_e_eid(Integer t_e_eid) {
        this.t_e_eid = t_e_eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.salmth
     *
     * @return the value of t_salary.salmth
     *
     * @mbggenerated
     */
    public Date getSalmth() {
        return salmth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.salmth
     *
     * @param salmth the value for t_salary.salmth
     *
     * @mbggenerated
     */
    public void setSalmth(Date salmth) {
        this.salmth = salmth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.basicsalary
     *
     * @return the value of t_salary.basicsalary
     *
     * @mbggenerated
     */
    public Integer getBasicsalary() {
        return basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.basicsalary
     *
     * @param basicsalary the value for t_salary.basicsalary
     *
     * @mbggenerated
     */
    public void setBasicsalary(Integer basicsalary) {
        this.basicsalary = basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.meritsal
     *
     * @return the value of t_salary.meritsal
     *
     * @mbggenerated
     */
    public Integer getMeritsal() {
        return meritsal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.meritsal
     *
     * @param meritsal the value for t_salary.meritsal
     *
     * @mbggenerated
     */
    public void setMeritsal(Integer meritsal) {
        this.meritsal = meritsal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.isbuysb
     *
     * @return the value of t_salary.isbuysb
     *
     * @mbggenerated
     */
    public Integer getIsbuysb() {
        return isbuysb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.isbuysb
     *
     * @param isbuysb the value for t_salary.isbuysb
     *
     * @mbggenerated
     */
    public void setIsbuysb(Integer isbuysb) {
        this.isbuysb = isbuysb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.addsal
     *
     * @return the value of t_salary.addsal
     *
     * @mbggenerated
     */
    public Integer getAddsal() {
        return addsal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.addsal
     *
     * @param addsal the value for t_salary.addsal
     *
     * @mbggenerated
     */
    public void setAddsal(Integer addsal) {
        this.addsal = addsal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.addmeritsal
     *
     * @return the value of t_salary.addmeritsal
     *
     * @mbggenerated
     */
    public Integer getAddmeritsal() {
        return addmeritsal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.addmeritsal
     *
     * @param addmeritsal the value for t_salary.addmeritsal
     *
     * @mbggenerated
     */
    public void setAddmeritsal(Integer addmeritsal) {
        this.addmeritsal = addmeritsal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.saldesc
     *
     * @return the value of t_salary.saldesc
     *
     * @mbggenerated
     */
    public String getSaldesc() {
        return saldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.saldesc
     *
     * @param saldesc the value for t_salary.saldesc
     *
     * @mbggenerated
     */
    public void setSaldesc(String saldesc) {
        this.saldesc = saldesc == null ? null : saldesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salary.salstate
     *
     * @return the value of t_salary.salstate
     *
     * @mbggenerated
     */
    public Integer getSalstate() {
        return salstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salary.salstate
     *
     * @param salstate the value for t_salary.salstate
     *
     * @mbggenerated
     */
    public void setSalstate(Integer salstate) {
        this.salstate = salstate;
    }
}